name: AutoBuild-QQwebhook-MultiPlatform

on:
  push:
    paths-ignore: 
      - '​**​/*.md'
      - '​**​/*.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10']
        include:
          - os: ubuntu-latest
            ext: ''
            build-deps: "sudo apt-get install -y build-essential python3-dev"
          - os: windows-latest
            ext: '.exe'
            build-deps: "echo 'Windows无需额外系统依赖'"
      fail-fast: false

    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install system dependencies
      if: matrix.os == 'ubuntu-latest'
      run: ${{ matrix.build-deps }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '​**​/requirements.txt'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ​**​/__pycache__
        key: ${{ runner.os }}-pip-${{ hashFiles('​**​/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install cython==0.29.36

    - name: Install dependencies
      run: |
        pip install -r requirements.txt pyinstaller
        pip check

    - name: Clean workspace
      run: |
        rm -rf dist build __pycache__ || rmdir /s /q dist build __pycache__

    - name: Build executable
      run: |
        pyinstaller --onefile --name qqwebhook${{ matrix.ext }} main.py
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          chmod +x dist/qqwebhook.exe
        fi

    - name: Package artifacts
      run: |
        mkdir release
        
        # 跨平台文件拷贝
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          copy dist\\qqwebhook.exe release\\
        else
          cp dist/qqwebhook release/
        fi

        # 生成时间戳（兼容Windows）
        TIMESTAMP=$(date +%Y%m%d)
        
        # 压缩打包
        cd release && zip -r ../qqwebhook-$TIMESTAMP-${{ matrix.os }}.zip ./*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: qqwebhook-${{ matrix.os }}
        path: |
          qqwebhook-*.zip
        retention-days: 7

    # 安全扫描（可选）
    - name: Dependency audit
      if: always()
      run: pip-audit --require-hashes -r requirements.txt
