name: AutoBuild-QQwebhook-ZIP

on:
  push:
    paths-ignore: 
      - 'README.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 新增系统构建依赖安装
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install cython==0.29.36  # 显式安装 Cython

    - name: Install dependencies
      run: |
        pip install -r requirements.txt pyinstaller
        pip check

    - name: Clean workspace
      run: rm -rf dist build __pycache__

    - name: Build executable
      run: |
        pyinstaller --onefile --name qqwebhook main.py
        file dist/qqwebhook
        chmod +x dist/qqwebhook

    - name: Create ZIP package
      run: |
        mkdir -p release
        
        # 跨平台兼容处理（网页5核心技巧）
        cp dist/qqwebhook release/
        # cp -r static/ release/  # 静态资源
        
        # 生成日期戳（网页5时间戳规范）
        TIMESTAMP=$(date +%Y%m%d)
        
        # 压缩命令（网页2+网页5最佳实践）
        cd release && zip -r ../qqwebhook-$TIMESTAMP.zip ./*
        
        # Windows兼容性处理（网页6路径规范）
        echo "::set-output name=zip_name::qqwebhook-$TIMESTAMP.zip"
      id: zip_pack

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: qqwebhook-build
        path: |
          qqwebhook-*.zip
        retention-days: 7
